"""Инициализация модуля стилей"""

from .base import (
    APP_STYLES,
    SEARCH_STYLES,
    NOTES_STYLES,
    PASSWORD_STATUS_STYLES,
    AUTH_STYLES,
    SETTINGS_GROUPBOX_STYLES
)

from .components import (
    WINDOW_CONTROL_STYLES,
    PASSWORD_LIST_STYLES,
    TAGS_CONTAINER_STYLES,
    PANEL_STYLES,
    OVERLAY_MESSAGE_STYLES
)

from .widgets import (
    CHIP_STYLES,
    LAZY_ICON_STYLES,
    PASSWORD_STATUS_WIDGET_STYLES,
    SKIP_BUTTON_STYLES,
    ADD_BUTTON_STYLES
)

from .dialogs import (
    PASSWORD_GENERATOR_STYLES,
    DIALOG_TITLE_BAR_STYLES,
    SETTINGS_DIALOG_STYLES,
    CONFIRM_DIALOG_STYLES
)

__all__ = [
    # Base styles
    'APP_STYLES',
    'SEARCH_STYLES',
    'NOTES_STYLES',
    'PASSWORD_STATUS_STYLES',
    'AUTH_STYLES',
    'SETTINGS_GROUPBOX_STYLES',
    
    # Component styles
    'WINDOW_CONTROL_STYLES',
    'PASSWORD_LIST_STYLES',
    'TAGS_CONTAINER_STYLES',
    'PANEL_STYLES',
    'OVERLAY_MESSAGE_STYLES',
    
    # Widget styles
    'CHIP_STYLES',
    'LAZY_ICON_STYLES',
    'PASSWORD_STATUS_WIDGET_STYLES',
    'SKIP_BUTTON_STYLES',
    'ADD_BUTTON_STYLES',
    
    # Dialog styles
    'PASSWORD_GENERATOR_STYLES',
    'DIALOG_TITLE_BAR_STYLES',
    'SETTINGS_DIALOG_STYLES',
    'CONFIRM_DIALOG_STYLES'
] 