from .base import (
    APP_STYLES as DEFAULT_APP_STYLES,
    SEARCH_STYLES as DEFAULT_SEARCH_STYLES,
    NOTES_STYLES as DEFAULT_NOTES_STYLES,
    PASSWORD_STATUS_STYLES as DEFAULT_PASSWORD_STATUS_STYLES,
    AUTH_STYLES as DEFAULT_AUTH_STYLES,
    SETTINGS_GROUPBOX_STYLES as DEFAULT_SETTINGS_GROUPBOX_STYLES
)
from .components import (
    WINDOW_CONTROL_STYLES as DEFAULT_WINDOW_CONTROL_STYLES,
    WINDOW_BUTTON_STYLES as DEFAULT_WINDOW_BUTTON_STYLES,
    PASSWORD_LIST_STYLES as DEFAULT_PASSWORD_LIST_STYLES,
    PANEL_STYLES as DEFAULT_PANEL_STYLES,
    OVERLAY_MESSAGE_STYLES as DEFAULT_OVERLAY_MESSAGE_STYLES,
    TAGS_CONTAINER_STYLES as DEFAULT_TAGS_CONTAINER_STYLES
)
from .widgets import (
    CHIP_WIDGET_STYLES as DEFAULT_CHIP_WIDGET_STYLES,
    CHIP_LABEL_STYLES as DEFAULT_CHIP_LABEL_STYLES,
    PASSWORD_STRENGTH_COLORS as DEFAULT_PASSWORD_STRENGTH_COLORS,
    ADD_BUTTON_STYLES as DEFAULT_ADD_BUTTON_STYLES,
    SKIP_BUTTON_STYLES as DEFAULT_SKIP_BUTTON_STYLES,
    CONTINUE_BUTTON_STYLES as DEFAULT_CONTINUE_BUTTON_STYLES,
    THEME_COMBOBOX_STYLES as DEFAULT_THEME_COMBOBOX_STYLES
)
from .dialogs import (
    PASSWORD_GENERATOR_STYLES as DEFAULT_PASSWORD_GENERATOR_STYLES,
    DIALOG_TITLE_BAR_STYLES as DEFAULT_DIALOG_TITLE_BAR_STYLES,
    SETTINGS_DIALOG_STYLES as DEFAULT_SETTINGS_DIALOG_STYLES,
    CONFIRM_DIALOG_STYLES as DEFAULT_CONFIRM_DIALOG_STYLES
)
from .cyberpunk_theme import (
    APP_STYLES as CYBERPUNK_APP_STYLES,
    SEARCH_STYLES as CYBERPUNK_SEARCH_STYLES,
    NOTES_STYLES as CYBERPUNK_NOTES_STYLES,
    PASSWORD_STATUS_STYLES as CYBERPUNK_PASSWORD_STATUS_STYLES,
    AUTH_STYLES as CYBERPUNK_AUTH_STYLES,
    SETTINGS_GROUPBOX_STYLES as CYBERPUNK_SETTINGS_GROUPBOX_STYLES,
    WINDOW_CONTROL_STYLES as CYBERPUNK_WINDOW_CONTROL_STYLES,
    PASSWORD_LIST_STYLES as CYBERPUNK_PASSWORD_LIST_STYLES,
    TAGS_CONTAINER_STYLES as CYBERPUNK_TAGS_CONTAINER_STYLES,
    PANEL_STYLES as CYBERPUNK_PANEL_STYLES,
    OVERLAY_MESSAGE_STYLES as CYBERPUNK_OVERLAY_MESSAGE_STYLES,
    ADD_BUTTON_STYLES as CYBERPUNK_ADD_BUTTON_STYLES,
    SKIP_BUTTON_STYLES as CYBERPUNK_SKIP_BUTTON_STYLES
)

THEMES = {
    "default": {
        "APP_STYLES": DEFAULT_APP_STYLES,
        "SEARCH_STYLES": DEFAULT_SEARCH_STYLES,
        "NOTES_STYLES": DEFAULT_NOTES_STYLES,
        "PASSWORD_STATUS_STYLES": DEFAULT_PASSWORD_STATUS_STYLES,
        "AUTH_STYLES": DEFAULT_AUTH_STYLES,
        "SETTINGS_GROUPBOX_STYLES": DEFAULT_SETTINGS_GROUPBOX_STYLES,
        "WINDOW_CONTROL_STYLES": DEFAULT_WINDOW_CONTROL_STYLES,
        "WINDOW_BUTTON_STYLES": DEFAULT_WINDOW_BUTTON_STYLES,
        "PASSWORD_LIST_STYLES": DEFAULT_PASSWORD_LIST_STYLES,
        "TAGS_CONTAINER_STYLES": DEFAULT_TAGS_CONTAINER_STYLES,
        "PANEL_STYLES": DEFAULT_PANEL_STYLES,
        "OVERLAY_MESSAGE_STYLES": DEFAULT_OVERLAY_MESSAGE_STYLES["default"],
        "CHIP_WIDGET_STYLES": DEFAULT_CHIP_WIDGET_STYLES["default"],
        "CHIP_LABEL_STYLES": DEFAULT_CHIP_LABEL_STYLES["default"],
        "PASSWORD_STRENGTH_COLORS": DEFAULT_PASSWORD_STRENGTH_COLORS["default"],
        "ADD_BUTTON_STYLES": DEFAULT_ADD_BUTTON_STYLES,
        "SKIP_BUTTON_STYLES": DEFAULT_SKIP_BUTTON_STYLES,
        "CONTINUE_BUTTON_STYLES": DEFAULT_CONTINUE_BUTTON_STYLES,
        "THEME_COMBOBOX_STYLES": DEFAULT_THEME_COMBOBOX_STYLES["default"]
    },
    "cyberpunk": {
        "APP_STYLES": CYBERPUNK_APP_STYLES,
        "SEARCH_STYLES": CYBERPUNK_SEARCH_STYLES,
        "NOTES_STYLES": CYBERPUNK_NOTES_STYLES,
        "PASSWORD_STATUS_STYLES": CYBERPUNK_PASSWORD_STATUS_STYLES,
        "AUTH_STYLES": CYBERPUNK_AUTH_STYLES,
        "SETTINGS_GROUPBOX_STYLES": CYBERPUNK_SETTINGS_GROUPBOX_STYLES,
        "WINDOW_CONTROL_STYLES": CYBERPUNK_WINDOW_CONTROL_STYLES,
        "WINDOW_BUTTON_STYLES": DEFAULT_WINDOW_BUTTON_STYLES,
        "PASSWORD_LIST_STYLES": CYBERPUNK_PASSWORD_LIST_STYLES,
        "TAGS_CONTAINER_STYLES": CYBERPUNK_TAGS_CONTAINER_STYLES,
        "PANEL_STYLES": CYBERPUNK_PANEL_STYLES,
        "OVERLAY_MESSAGE_STYLES": DEFAULT_OVERLAY_MESSAGE_STYLES["cyberpunk"],
        "CHIP_WIDGET_STYLES": DEFAULT_CHIP_WIDGET_STYLES["cyberpunk"],
        "CHIP_LABEL_STYLES": DEFAULT_CHIP_LABEL_STYLES["cyberpunk"],
        "PASSWORD_STRENGTH_COLORS": DEFAULT_PASSWORD_STRENGTH_COLORS["cyberpunk"],
        "ADD_BUTTON_STYLES": CYBERPUNK_ADD_BUTTON_STYLES,
        "SKIP_BUTTON_STYLES": CYBERPUNK_SKIP_BUTTON_STYLES,
        "CONTINUE_BUTTON_STYLES": DEFAULT_AUTH_STYLES,
        "THEME_COMBOBOX_STYLES": DEFAULT_THEME_COMBOBOX_STYLES["cyberpunk"]
    }
} 