from .base import (
    APP_STYLES as DEFAULT_APP_STYLES,
    SEARCH_STYLES as DEFAULT_SEARCH_STYLES,
    NOTES_STYLES as DEFAULT_NOTES_STYLES,
    PASSWORD_STATUS_STYLES as DEFAULT_PASSWORD_STATUS_STYLES,
    AUTH_STYLES as DEFAULT_AUTH_STYLES,
    SETTINGS_GROUPBOX_STYLES as DEFAULT_SETTINGS_GROUPBOX_STYLES
)
from .components import (
    WINDOW_CONTROL_STYLES as DEFAULT_WINDOW_CONTROL_STYLES,
    PASSWORD_LIST_STYLES as DEFAULT_PASSWORD_LIST_STYLES,
    TAGS_CONTAINER_STYLES as DEFAULT_TAGS_CONTAINER_STYLES,
    PANEL_STYLES as DEFAULT_PANEL_STYLES,
    OVERLAY_MESSAGE_STYLES as DEFAULT_OVERLAY_MESSAGE_STYLES
)
from .widgets import (
    CHIP_STYLES as DEFAULT_CHIP_STYLES,
    LAZY_ICON_STYLES as DEFAULT_LAZY_ICON_STYLES,
    PASSWORD_STATUS_WIDGET_STYLES as DEFAULT_PASSWORD_STATUS_WIDGET_STYLES,
    SKIP_BUTTON_STYLES as DEFAULT_SKIP_BUTTON_STYLES,
    ADD_BUTTON_STYLES as DEFAULT_ADD_BUTTON_STYLES
)
from .dialogs import (
    PASSWORD_GENERATOR_STYLES as DEFAULT_PASSWORD_GENERATOR_STYLES,
    DIALOG_TITLE_BAR_STYLES as DEFAULT_DIALOG_TITLE_BAR_STYLES,
    SETTINGS_DIALOG_STYLES as DEFAULT_SETTINGS_DIALOG_STYLES,
    CONFIRM_DIALOG_STYLES as DEFAULT_CONFIRM_DIALOG_STYLES
)
from .cyberpunk_theme import (
    APP_STYLES as CYBER_APP_STYLES,
    SEARCH_STYLES as CYBER_SEARCH_STYLES,
    NOTES_STYLES as CYBER_NOTES_STYLES,
    PANEL_STYLES as CYBER_PANEL_STYLES,
    TAGS_CONTAINER_STYLES as CYBER_TAGS_CONTAINER_STYLES,
    PASSWORD_LIST_STYLES as CYBER_PASSWORD_LIST_STYLES,
    WINDOW_CONTROL_STYLES as CYBER_WINDOW_CONTROL_STYLES,
    OVERLAY_MESSAGE_STYLES as CYBER_OVERLAY_MESSAGE_STYLES,
    CHIP_STYLES as CYBER_CHIP_STYLES,
    PASSWORD_STATUS_WIDGET_STYLES as CYBER_PASSWORD_STATUS_WIDGET_STYLES,
    SKIP_BUTTON_STYLES as CYBER_SKIP_BUTTON_STYLES,
    ADD_BUTTON_STYLES as CYBER_ADD_BUTTON_STYLES,
    PASSWORD_GENERATOR_STYLES as CYBER_PASSWORD_GENERATOR_STYLES,
    DIALOG_TITLE_BAR_STYLES as CYBER_DIALOG_TITLE_BAR_STYLES,
    SETTINGS_DIALOG_STYLES as CYBER_SETTINGS_DIALOG_STYLES,
    CONFIRM_DIALOG_STYLES as CYBER_CONFIRM_DIALOG_STYLES
)

THEMES = {
    "default": {
        "APP_STYLES": DEFAULT_APP_STYLES,
        "SEARCH_STYLES": DEFAULT_SEARCH_STYLES,
        "NOTES_STYLES": DEFAULT_NOTES_STYLES,
        "PASSWORD_STATUS_STYLES": DEFAULT_PASSWORD_STATUS_STYLES,
        "AUTH_STYLES": DEFAULT_AUTH_STYLES,
        "SETTINGS_GROUPBOX_STYLES": DEFAULT_SETTINGS_GROUPBOX_STYLES,
        "WINDOW_CONTROL_STYLES": DEFAULT_WINDOW_CONTROL_STYLES,
        "PASSWORD_LIST_STYLES": DEFAULT_PASSWORD_LIST_STYLES,
        "TAGS_CONTAINER_STYLES": DEFAULT_TAGS_CONTAINER_STYLES,
        "PANEL_STYLES": DEFAULT_PANEL_STYLES,
        "OVERLAY_MESSAGE_STYLES": DEFAULT_OVERLAY_MESSAGE_STYLES,
        "CHIP_STYLES": DEFAULT_CHIP_STYLES,
        "LAZY_ICON_STYLES": DEFAULT_LAZY_ICON_STYLES,
        "PASSWORD_STATUS_WIDGET_STYLES": DEFAULT_PASSWORD_STATUS_WIDGET_STYLES,
        "SKIP_BUTTON_STYLES": DEFAULT_SKIP_BUTTON_STYLES,
        "ADD_BUTTON_STYLES": DEFAULT_ADD_BUTTON_STYLES,
        "PASSWORD_GENERATOR_STYLES": DEFAULT_PASSWORD_GENERATOR_STYLES,
        "DIALOG_TITLE_BAR_STYLES": DEFAULT_DIALOG_TITLE_BAR_STYLES,
        "SETTINGS_DIALOG_STYLES": DEFAULT_SETTINGS_DIALOG_STYLES,
        "CONFIRM_DIALOG_STYLES": DEFAULT_CONFIRM_DIALOG_STYLES
    },
    "cyberpunk": {
        "APP_STYLES": CYBER_APP_STYLES,
        "SEARCH_STYLES": CYBER_SEARCH_STYLES,
        "NOTES_STYLES": CYBER_NOTES_STYLES,
        "PANEL_STYLES": CYBER_PANEL_STYLES,
        "TAGS_CONTAINER_STYLES": CYBER_TAGS_CONTAINER_STYLES,
        "PASSWORD_LIST_STYLES": CYBER_PASSWORD_LIST_STYLES,
        "WINDOW_CONTROL_STYLES": CYBER_WINDOW_CONTROL_STYLES,
        "OVERLAY_MESSAGE_STYLES": CYBER_OVERLAY_MESSAGE_STYLES,
        "CHIP_STYLES": CYBER_CHIP_STYLES,
        "PASSWORD_STATUS_WIDGET_STYLES": CYBER_PASSWORD_STATUS_WIDGET_STYLES,
        "SKIP_BUTTON_STYLES": CYBER_SKIP_BUTTON_STYLES,
        "ADD_BUTTON_STYLES": CYBER_ADD_BUTTON_STYLES,
        "PASSWORD_GENERATOR_STYLES": CYBER_PASSWORD_GENERATOR_STYLES,
        "DIALOG_TITLE_BAR_STYLES": CYBER_DIALOG_TITLE_BAR_STYLES,
        "SETTINGS_DIALOG_STYLES": CYBER_SETTINGS_DIALOG_STYLES,
        "CONFIRM_DIALOG_STYLES": CYBER_CONFIRM_DIALOG_STYLES
    }
} 